{"description":"The following method will create two ExceptionalYield instead of one. This is because the path returning from the catch is considered as an exceptional one : the SV returned is an exceptionalSymbolicValue and the path is not considered as an happy path even though the exception was caught. \r\n{code}\r\n  private Exception returningException() {\r\n    try {\r\n      doSomething();\r\n    } catch (Exception e) {\r\n      return e;\r\n    }\r\n    return null;\r\n  }\r\n  abstract void doSomething() throws Exception;\r\n{code}\r\n\r\n","component":"SonarJava","component_version":"4.14"}