{"description":"In the following code, the exception which can be triggered by {{stream.read()}} should lead to the exit of the block, but it\u0027s not the case, as exceptions are badly branched.\r\n\r\n{code}\r\nimport java.io.FileInputStream;\r\n\r\nclass A {\r\n\r\n  public void forLoopHandling(int maxLoop) throws Exception {\r\n    FileInputStream stream;\r\n    for (int i \u003d 0; i \u003c maxLoop; i++) {\r\n      stream \u003d new FileInputStream(\"myFile\");\r\n      stream.read(); // can fail and lead to B0, having the stream not closed.\r\n      stream.close();\r\n    }\r\n  }\r\n}\r\n{code}","component":"SonarJava","component_version":"4.6"}